name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Pytest
            command: uv run pytest
          - name: Mypy
            command: uv run mypy scripts/
          - name: Ruff
            command: uv run ruff check --output-format github --preview
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --group dev
      - name: Run checks
        run: ${{ matrix.command }}
