name: Crawl Registry

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  push:
    branches:
      - package_control_channel

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: crawler-status
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Ensure wrk directory exists
        run: mkdir -p ./wrk

      - name: Restore wrk cache
        uses: actions/cache@v4
        with:
          path: ./wrk
          key: wrk-cache-${{ github.run_id }}
          restore-keys: |
            wrk-cache-

      - name: Generate registry
        run: uv run -m scripts.generate_registry -o ./wrk/registry.json

      - name: Run crawler
        run: |
          set -o pipefail
          PYTHONUNBUFFERED=1 uv run -m scripts.crawl --limit 1000 \
            --registry ./wrk/registry.json \
            --workspace ./wrk/workspace.json \
            2>&1 | tee crawl.log

      - name: Generate channel
        run: |
          set -o pipefail
          PYTHONUNBUFFERED=1 uv run -m scripts.generate_channel \
            --registry ./wrk/registry.json \
            --workspace ./wrk/workspace.json \
            -o ./wrk/channel.json \
            2>&1 | tee channel.log

      - name: Update release notes
        run: |
          # Create or update the release
          gh release view ${{ env.RELEASE_TAG }} > /dev/null || \
          gh release create ${{ env.RELEASE_TAG }} \
            --title "The Crawler Logs" \
            --notes "..." \
            --latest=false

          echo "Uploading working dir files..."
          gh release upload ${{ env.RELEASE_TAG }} ./wrk/channel.json --clobber
          gh release upload ${{ env.RELEASE_TAG }} ./wrk/registry.json --clobber
          gh release upload ${{ env.RELEASE_TAG }} ./wrk/workspace.json --clobber

          DATE=$(TZ=Europe/Berlin date +"%B %d, %Y, %H:%M GMT%:::z" | sed -E 's/([+-])0/\1/')
          REPO_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          # Build new notes
          {
            echo "$DATE  ([logs]($REPO_URL))"
            echo ""
            # Insert a blank line before lines that are exactly '---'
            awk '{ if ($0 == "---") print ""; print }' crawl.log
            echo ""
            echo "---"
            cat channel.log
          } > notes.txt

          echo "Updating release notes..."
          gh release edit ${{ env.RELEASE_TAG }} --notes-file notes.txt
